### ISSUE TITLE
Feature request - command to generate OpenAPI specification file

### ISSUE THREAD

**Issue by vylink** [apitte/openapi#7]
It will be really nice to have a tool to generate and save the OpenAPI specification file from annotations.
Ideally with option to save it as a JSON or YAML format.

**Comment by mabar** [comment]
```php
__construct(OpenApiService $service)
{
    $schema = $service->createSchema;
    $this->jsonSchema = \Nette\Utils\Json::encode($schema->toArray());
}
```

**Comment by f3l1x** [comment]
It could be done in apitte/console, WDYT?

**Comment by mabar** [comment]
https://github.com/apitte/console/issues/6
